yarnPath: .yarn/releases/yarn-4.2.1.cjs
compressionLevel: 0
defaultSemverRangePrefix: ''
enableGlobalCache: false
nmMode: hardlinks-local
nodeLinker: node-modules
checksumBehavior: update
supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
